#!/usr/bin/env python3

import zipfile
import os
import datetime

def create_zip_archive():
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    prefix = f"inf2171-232-tp1_{timestamp}"
    archive_name = f"{prefix}.zip"

    with zipfile.ZipFile(archive_name, "w", zipfile.ZIP_DEFLATED) as zipf:
        for root, _, files in os.walk("."):
            for file in files:
                if not file.endswith(".s"):
                    continue
                file_path = os.path.join(root, file)
                zipf.write(file_path, arcname=os.path.join(prefix, file))

    print(f"Zip archive created: {archive_name}")

create_zip_archive()
